spring:
  application:
    name: kafka-consumer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: kafka-check
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.example.consumer.dto
        spring.json.value.default.type: com.example.consumer.dto.ConsumerMessageDto
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topic: demo-topic
    dlt-topic: demo-topic-dlt
    retry-attempts: 10
    retry-interval-ms: 5000
  mongodb:
    consumer-collection: kafka_log
    dlt-collection: kafka_dlt_log

logging:
  level:
    root: INFO
    com.example.consumer: INFO
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
